<?php
/**
 * Magmodules.eu
 * http://www.magmodules.eu
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magmodules.eu so we can send you a copy immediately.
 *
 * @category    Magmodules
 * @package     Magmodules_Colorbox
 * @author      Magmodules <info@magmodules.eu)
 * @copyright   Copyright (c) 2013 (http://www.magmodules.eu)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

 $_product = $this->getProduct();
 $_helper  = $this->helper('catalog/output');
 $colorbox = Mage::helper('colorbox');

 // Sizes
 $popupsize = explode(',', $colorbox->getPopupSize());
 $mainsize = explode(',', $colorbox->getMainSize());
 $thumbsize = explode(',', $colorbox->getThumbSize());
?>

<?php if(Mage::getStoreConfig('colorbox/settings/jquery') == 'google'): ?>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<?php endif; ?>

<?php if(Mage::getStoreConfig('colorbox/settings/jquery') == 'local'): ?>
	<script src="<?php echo $this->getSkinUrl('magmodules/colorbox/jquery.min.js'); ?>"></script>
<?php endif; ?>

<script src="<?php echo $this->getSkinUrl('magmodules/colorbox/jquery.colorbox-min.js'); ?>" type="text/javascript"></script>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('magmodules/colorbox/'. Mage::getStoreConfig('colorbox/theme/theme') .'/colorbox.css'); ?>" type="text/css" media="screen" />
<script>
	jQuery.noConflict();
	jQuery(document).ready(function(){
			jQuery(".colorbox").colorbox(
				{
					rel:'colorbox',
					current: "<?php echo Mage::helper('colorbox')->__('Image {current} of {total}') ?>",
					previous: "<?php echo Mage::helper('colorbox')->__('previous') ?>",
					next: "<?php echo Mage::helper('colorbox')->__('next') ?>",
					close: "<?php echo Mage::helper('colorbox')->__('close') ?>",
					transition: "<?php echo Mage::getStoreConfig('colorbox/theme/transition') ?>",
					speed: "<?php echo Mage::getStoreConfig('colorbox/theme/transition_speed') ?>"										      
				}
		);
	});
</script>

<p class="product-image">
   <a id="productimagemain" class="colorbox" href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->keepFrame(false)->resize($popupsize[0],$popupsize[1]); ?>">
       <?php
           $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->keepFrame(false)->resize($mainsize[0],$mainsize[1]).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
           echo $_helper->productAttribute($_product, $_img, 'image');
       ?>
   </a>     
</p>

<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views">
	<h2><?php echo $this->__('More Views') ?></h2>
	<ul> 
	<?php $i=0; foreach ($this->getGalleryImages() as $_image): ?>
		<li>
			<a class="colorbox" href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->keepFrame(false)->resize($popupsize[0],$popupsize[1]); ?>"  title="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
				<img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->keepFrame(false)->resize($thumbsize[0],$thumbsize[1]); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
			</a>
		</li>
	<?php $i++ ?>
	<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>