<?php if($this->getCollection()->getSize()): ?>
    <div class="toolbar">
    <?php if( $this->isExpanded() ): ?>
        <div class="sort-by">
            <label><?php echo $this->__('Sort By') ?></label>
            <select onchange="setLocation(this.value)">
                <?php var_dump($this->getName()); ?>
                <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                    <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                        <?php echo $this->__($_order) ?>
                    </option>
                <?php endforeach; ?>
            </select>
       </div>
    <?php endif; ?>
    </div>
<?php endif ?>
