
<?php 
    $product_items = $this->getProductSlideShow(); 
    
    foreach ($product_items as  $product){
     //  var_dump($product);
    }
   $base_url =Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
?>
<script type="text/javascript" src="<?php echo $base_url;?>/js/jquery.min.1-5.js"></script>
<script type="text/javascript" src="<?php echo $base_url;?>/js/jquery.cycle.all.latest.js"></script>
<script type="text/javascript">
    $.noConflict();
    (function($) {
        jQuery(document).ready(function() {     
                
            $('.slideshow').cycle({
                delay:  4000, 
                speed:  1000, 
  
                fx: 'fade', // choose your transition type, ex: fade, scrollUp, shuffle, etc...
                prev:   '#prev', 
                next:   '#next',
                pager:   '#nav', 
                //pagerEvent: 'mouseover',
                timeout: 4000,
                pagerAnchorBuilder: function(idx, slide) { 
                    // return selector string for existing anchor 
                    return '#nav li:eq(' + idx + ') a'; 
                }     
            }); 
 
            $('#direct').click(function() { 
                $('#nav li:eq(2) a').trigger('click'); 
                return false; 
            }); 

	
        });
    })(jQuery);
           
</script>
<div class="slidePaging"><a href="#" id="prev">Previous </a><a href="#" id="next">Next</a></div>
<div class="slideshow">    
            
                <?php 
                    $product_items = $this->getProductSlideShow(); 
                    $pathimg = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'gallery/';
//                    if ($this->getUrl('') == $this->getUrl('*/*/*', array('_current' => true, '_use_rewrite' => true))) { 
                    foreach ($product_items as  $product) { ?>
                        <a class="clearfix" href="#" >
                            <!--<span class="caption"><?php echo $product['description']?></span>--> 
                            <img src = "<?php echo $pathimg.$product['filename'] ?>" width ="250px" height = "385px" alt=""/>
                        </a>
                <?php }  ?>
               
                
            
     
    </div>

                            